### ISSUE TITLE
Angular.json is missing : Local workspace file ('angular.json') could not be found.

### ISSUE THREAD

**Issue by brnrajoriya** [cornflourblue/angular-6-jwt-authentication-example#1]
[
![screenshot_5](https://user-images.githubusercontent.com/9497444/42758138-0b36c27c-8920-11e8-996d-ecdd8927d396.png)
](url)

**Comment by azad-karimyan** [comment]
same problem

**Comment by cornflourblue** [comment]
This project doesn't use angular cli, run with `npm start`
